bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /mybot_controller/odom
    transform_tolerance: 0.3
    default_server_timeout: 1000
    bt_loop_duration: 10
    wait_for_service_timeout: 1000
    # IMPORTANT: You must change the username "alien" to your username "raspberry" in the paths below
    default_nav_to_pose_bt_xml: "/home/raspberry/Learn-by-Doing-Plan-Navigation/mybot_ws/src/mybot_navigation/behavior_tree/simple_navigation_w_replanning_and_recovery.xml" # <-- CORRECTED PATH
    default_nav_through_poses_bt_xml: "/home/raspberry/Learn-by-Doing-Plan-Navigation/mybot_ws/src/mybot_navigation/behavior_tree/simple_navigation_w_replanning_and_recovery.xml" # <-- CORRECTED PATH

    