rplidar_node:
  ros__parameters:
    channel_type: serial
    serial_port: /dev/lidar
    serial_baudrate: 115200
    frame_id: laser_link
    inverted: false
    angle_compensate: true
    scan_mode: Sensitivity